package aed1.solitario.SolitarioDesdeCero;
public enum Accion {
	SACAR_DE_BARAJA, 
	SACAR_DE_DESCARTE, 
	METER_EN_DESCARTE, 
	SACAR_DE_MONTON_FINAL, 
	METER_EN_MONTON_FINAL, 
	SACAR_DE_MONTON_INTERMEDIO, 
	METER_EN_MONTON_INTERMEDIO, 
	SALIR
}